export const SET_USERS = 'SET_USERS';
export const SET_SELECT_OPTION = 'SET_SELECT_OPTION';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SORT_CONFIG = 'SET_SORT_CONFIG';
export const SET_USER = 'SET_USER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'; 